"""The harness: the gate, the ledger row and the grammar every engine runs behind (README §3.1).

One package sits between the lane and whatever produces tokens. It owns the three hooks and the
``OP:`` grammar, and it depends on ``athena.core`` only through the ``Protocol``s in
:mod:`athena.harness.ports` — so the gate is testable with no SQLite, no subprocess and no
provider, and an engine is a configuration choice rather than a second policy (ADR 0007).
"""

from athena.harness.cli_harness import (
    CLAUDE,
    CLAUDE_EXTRA_ARGS,
    CODEX,
    DIALECTS,
    MAX_ROUNDS,
    TURN_TIMEOUT_S,
    CliDialect,
    CliHarness,
    Decoded,
)
from athena.harness.engines import (
    ENGINES,
    EngineStatus,
    build_harness,
    probe,
    probe_all,
)
from athena.harness.hooks import (
    Cancel,
    GateDecision,
    GateHook,
    GateOutcome,
    LedgerHook,
    Proceed,
    TruncationHook,
    TurnFlag,
)
from athena.harness.op_grammar import Op, OpError, ParsedTurn, parse_op, parse_turn
from athena.harness.policy import (
    LivenessPort,
    PolicyCatalog,
    Rule,
    StructuralPolicy,
    connector_enabled,
    default_policy,
    entries_by_name,
    lane_enabled,
    same_origin,
)
from athena.harness.ports import (
    ApprovalsPort,
    Card,
    CatalogPort,
    FlagPort,
    Grant,
    LedgerPort,
    ModelChunk,
    ModelFn,
    ModelMessage,
    ModelRequest,
    Row,
    stream_of,
)
from athena.harness.transports import (
    CliRequest,
    ScriptedTransport,
    SubprocessTransport,
    Transport,
    TransportError,
    rounds_from_transcript,
)

__all__ = [
    "CLAUDE",
    "CLAUDE_EXTRA_ARGS",
    "CODEX",
    "DIALECTS",
    "ENGINES",
    "MAX_ROUNDS",
    "TURN_TIMEOUT_S",
    "ApprovalsPort",
    "Cancel",
    "Card",
    "CatalogPort",
    "CliDialect",
    "CliHarness",
    "CliRequest",
    "Decoded",
    "EngineStatus",
    "FlagPort",
    "GateDecision",
    "GateHook",
    "GateOutcome",
    "Grant",
    "LedgerHook",
    "LedgerPort",
    "LivenessPort",
    "ModelChunk",
    "ModelFn",
    "ModelMessage",
    "ModelRequest",
    "Op",
    "OpError",
    "ParsedTurn",
    "PolicyCatalog",
    "Proceed",
    "Row",
    "Rule",
    "ScriptedTransport",
    "StructuralPolicy",
    "SubprocessTransport",
    "Transport",
    "TransportError",
    "TruncationHook",
    "TurnFlag",
    "build_harness",
    "connector_enabled",
    "default_policy",
    "entries_by_name",
    "lane_enabled",
    "parse_op",
    "parse_turn",
    "probe",
    "probe_all",
    "rounds_from_transcript",
    "same_origin",
    "stream_of",
]
