"""The seams every package in this repository is written against (README §3.1).

Dataclasses and Protocols only: no I/O, no provider import, nothing that can fail at import time.
``core``, ``harness``, ``lane``, ``daemon`` and ``channels`` all depend on this package and never
on each other's concrete classes, which is what lets them be built in parallel. Forking one of
these types inside a package is a review blocker; changing one here needs a test.
"""

from athena.contracts.channel import (
    EVENT_KINDS,
    FAMILIES,
    ChannelEvent,
    DecisionKind,
    DecisionOption,
    DecisionRequested,
    DecisionResolved,
    TextDelta,
    ToolCall,
    ToolResult,
    TurnError,
    TurnFinished,
    TurnSummary,
    event_from_dict,
    event_from_json,
    family_of,
    now_iso,
)
from athena.contracts.harness import (
    ERROR_REASONS,
    Harness,
    PromptBlock,
    TurnResult,
    fnv1a_64,
    normalize_reason,
)
from athena.contracts.ids import (
    ID_KINDS,
    ID_PREFIXES,
    ID_SUFFIX_HEX,
    conversation_for_app,
    conversation_for_project,
    is_id,
    kind_of,
    mint,
    prefix_of,
)
from athena.contracts.manifest import (
    SIDE_EFFECTS,
    HostManifest,
    HostTool,
    SideEffects,
    StateReadable,
)
from athena.contracts.registry import (
    ALL_LANES,
    ExecResult,
    Executor,
    ExecutorFn,
    Lane,
    Tier,
    ToolClass,
    ToolEntry,
    ToolOrigin,
    TurnContext,
    ValidationResult,
    Validator,
    ValidatorFn,
    always_valid,
    is_origin,
    parse_origin,
)

__all__ = [
    "ALL_LANES",
    "ERROR_REASONS",
    "EVENT_KINDS",
    "FAMILIES",
    "ID_KINDS",
    "ID_PREFIXES",
    "ID_SUFFIX_HEX",
    "SIDE_EFFECTS",
    "ChannelEvent",
    "DecisionKind",
    "DecisionOption",
    "DecisionRequested",
    "DecisionResolved",
    "ExecResult",
    "Executor",
    "ExecutorFn",
    "Harness",
    "HostManifest",
    "HostTool",
    "Lane",
    "PromptBlock",
    "SideEffects",
    "StateReadable",
    "TextDelta",
    "Tier",
    "ToolCall",
    "ToolClass",
    "ToolEntry",
    "ToolOrigin",
    "ToolResult",
    "TurnContext",
    "TurnError",
    "TurnFinished",
    "TurnResult",
    "TurnSummary",
    "ValidationResult",
    "Validator",
    "ValidatorFn",
    "always_valid",
    "conversation_for_app",
    "conversation_for_project",
    "event_from_dict",
    "event_from_json",
    "family_of",
    "fnv1a_64",
    "is_id",
    "is_origin",
    "kind_of",
    "mint",
    "normalize_reason",
    "now_iso",
    "parse_origin",
    "prefix_of",
]
