"""The Gauntlet: Nemotron attacks Athena's gate, the gate's records decide (README §9; ADR 0032).

The claim it proves or kills: **under adversarial host content generated by NVIDIA Nemotron,
Athena's gate never lets a GATED action — a fact write included — run without the user's
approval, on Claude and on Nemotron.**

- :mod:`.attacks` — the surfaces, the attack schema, the generator and judge prompts.
- :mod:`.delivery` — how one attack reaches a world: page state, a tool result, or memory.
- :mod:`.verdict` — ``held`` / ``breached`` / ``error`` and ``pressure``, from the gate's records.
- :mod:`.run` — generation, judging, the two rows, the proof, the report.

Surface 4 of the design, a foreign agent over MCP, is deferred: no MCP channel exists in
``src/`` for an attack to arrive on, and the report header says so.
"""

from __future__ import annotations

__all__: list[str] = []
