/**
 * The token pipeline is retired, and this is what "retired" has to keep meaning.
 *
 * `design/build-tokens.mjs` compiles three DTCG inputs into three `components/<slug>/` directories
 * that do not exist, no npm script runs it, nothing imports its output, and the one direction that
 * ships hand-writes its tokens instead. Nothing in the gate could tell, which is why it sat
 * disconnected without a single failure.
 *
 * It is marked rather than deleted. This file is the upstream of record for two vendored copies
 * that document their divergence from it line by line (`examples/hirelane/design/build-tokens.mjs`,
 * `examples/ledgerbox/design/build-tokens.mjs`), `examples/ledgerbox/design/pass3-token-brief.md`
 * cites this app's brief by path as the precedent disposition, and it is the only implementation of
 * `--refs`. Deleting it would answer a dead-code finding by breaking four live citations in two
 * other apps. Both siblings had already made the same call for their own copies; this makes the
 * three read the same way.
 *
 * So the state this pins is the retirement itself, on both sides:
 *
 *   1. the hand-written file is the value authority and is really wired to the page;
 *   2. the pipeline is really disconnected - no script, no consumer, no output directory;
 *   3. every retired input says so, in its own `$description`, and names the live authority;
 *   4. the machinery still runs, which is the entire reason for keeping it.
 *
 * A future pass that chooses the other option - author `blocks.tokens.json` and make the pipeline
 * load-bearing - fails this file, which is correct: that is a direction, and it has to be taken
 * deliberately and written down here.
 *
 *   node --experimental-transform-types --import ./test/register.mjs --test "test/**\/*.test.ts"
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const from = (path: string): string => fileURLToPath(new URL(`../${path}`, import.meta.url));
const read = (path: string): string => readFileSync(from(path), "utf8");

/** The hand-written file DESIGN.md §2 names, and the only one a rendered page reads. */
const AUTHORITY = "components/blocks/style/base/tokens.css";
const EMITTER = "design/build-tokens.mjs";
const INPUTS = readdirSync(from("design/tokens")).filter((f) => f.endsWith(".tokens.json"));

test("the value authority is hand-written, scoped, and actually imported", () => {
  const tokens = read(AUTHORITY);
  assert.match(tokens, /\[data-variant="blocks"\]/, `${AUTHORITY} does not scope itself`);
  assert.ok(tokens.split("\n").length > 100, "the authority is the file carrying the values");
  assert.match(
    read("components/blocks/style/index.css"),
    /@import "\.\/base\/tokens\.css";/,
    "the authority is imported by the direction's stylesheet entry",
  );
  // Whatever else changes, the authority is not generated. A `GENERATED by` banner here means the
  // pipeline was wired up and this test is now describing the wrong world.
  assert.doesNotMatch(tokens, /GENERATED by/, `${AUTHORITY} is hand-written, or this test is stale`);
});

test("the pipeline is disconnected: no script, no consumer, no output directory", () => {
  const scripts = JSON.parse(read("package.json")).scripts as Record<string, string>;
  assert.deepEqual(
    Object.entries(scripts).filter(([, cmd]) => cmd.includes("build-tokens")),
    [],
    "an npm script runs the retired emitter",
  );

  // The variants the inputs are for, and the component trees they would build into.
  const variants = INPUTS.map((f) => f.replace(".tokens.json", ""));
  assert.ok(variants.length >= 3, "the retired inputs are still here to be checked");
  assert.deepEqual(
    variants.filter((v) => existsSync(from(`components/${v}`))),
    [],
    "a retired variant grew a component tree; the pipeline may no longer be disconnected",
  );
  assert.ok(
    !INPUTS.includes("blocks.tokens.json"),
    "a blocks input appeared: the pipeline is being wired to the live direction, which is a direction call",
  );

  // Nothing anywhere reads an emitted layer. `base/tokens.css` is the hand-written authority and
  // is matched by name, not by the `<slug>.tokens.css` shape the emitter writes.
  const emitted = /[a-z]+\.tokens\.css/g;
  for (const dir of ["app", "components", "lib"]) {
    for (const file of walk(from(dir))) {
      const hits = [...readFileSync(file, "utf8").matchAll(emitted)].map((m) => m[0]);
      assert.deepEqual(hits, [], `${file} references emitted token CSS`);
    }
  }
});

test("every retired input says it is retired and names the live authority", () => {
  for (const input of INPUTS) {
    const doc = JSON.parse(read(`design/tokens/${input}`)) as { $description?: string };
    const description = doc.$description ?? "";
    assert.match(description, /^RETIRED \(\d{4}-\d{2}\)/, `${input} carries no status marker`);
    assert.ok(
      description.includes(AUTHORITY),
      `${input} does not send a reader to the live value authority`,
    );
  }
  // And the emitter itself, which is the file a maintainer opens first.
  const emitter = read(EMITTER);
  assert.match(emitter, /RETIRED \(\d{4}-\d{2}\)/, `${EMITTER} carries no status marker`);
  assert.ok(emitter.includes(AUTHORITY), `${EMITTER} does not name the live value authority`);
  // The usage block used to spell out `../components/<slug>/`, a path that does not exist and that
  // `mkdirSync(recursive)` would have created rather than updated.
  assert.doesNotMatch(
    emitter,
    /\.\.\/components\/\$?\{?variant\}?\//,
    `${EMITTER} still advertises an output directory that does not exist`,
  );
});

test("the retired machinery still runs, which is why it is kept", () => {
  const out = mkdtempSync(join(tmpdir(), "tidycrm-tokens-"));
  for (const input of INPUTS) {
    const variant = input.replace(".tokens.json", "");
    const args = [from(EMITTER), variant, join(out, `${variant}.css`)];
    if (variant === "token") args.push("--refs");
    const log = execFileSync(process.execPath, args, { encoding: "utf8" });
    assert.match(log, /wrote \d+ custom properties/, `${variant} did not build`);
    const css = readFileSync(join(out, `${variant}.css`), "utf8");
    assert.match(css, new RegExp(`\\[data-variant="${variant}"\\]`), `${variant} lost its scope`);
    assert.match(css, /RETIRED/, `${variant}'s output does not say it is nobody's`);
  }
});

/** Every file under a directory, so "nothing imports the output" is checked against everything. */
function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return entry.name === "node_modules" ? [] : walk(path);
    return /\.(ts|tsx|css|mjs|js)$/.test(entry.name) ? [path] : [];
  });
}
