/**
 * The summary `export_summary` writes - design 4.6.1's close - in the two forms it is asked for.
 *
 * Plain text is what the reports view prints and a person pastes into a spreadsheet. Markdown is
 * what leaves the app: act 1 ends with the close becoming a page somewhere else, and a page needs
 * a title and a body, not a monospaced block whose columns collapse the moment they are rendered.
 * Both are rendered from the same `SummaryInput`, so the two can never say different numbers.
 */
import { PERIOD_LABEL, type Period } from "./constants";
import { formatMoney } from "./format";
import type { InvoiceRow, PeriodSummary } from "./types";

export interface SummaryInput {
  summary: PeriodSummary;
  /** Everything still owed in the period, largest balance first. */
  outstanding: InvoiceRow[];
}

/** Rows the "Still owed" table prints before it says how many it left out. */
const LIMIT = 12;

function pad(label: string): string {
  return label.padEnd(22, " ");
}

/** What the exported page is called: "August 2026 close". */
export function summaryTitle(period: Period): string {
  return `${PERIOD_LABEL[period]} close`;
}

export function renderSummary({ summary, outstanding }: SummaryInput): string {
  const head = [
    `Ledgerbox summary - ${PERIOD_LABEL[summary.period]}`,
    "".padEnd(46, "="),
    `${pad("Invoices issued")}${summary.invoice_count}`,
    `${pad("Invoiced")}${formatMoney(summary.invoiced_cents)}`,
    `${pad("Collected")}${formatMoney(summary.collected_cents)}`,
    `${pad("Outstanding")}${formatMoney(summary.outstanding_cents)}`,
    `${pad("Overdue")}${formatMoney(summary.overdue_cents)} across ${summary.overdue_count} invoices`,
    `${pad("Disputed")}${summary.disputed_count}`,
    `${pad("Bank lines unapplied")}${summary.unmatched_lines} worth ${formatMoney(summary.unmatched_cents)}`,
  ];

  const shown = outstanding.slice(0, LIMIT);
  const hidden = outstanding.slice(LIMIT);

  const rows = shown.map(
    (r) =>
      `${r.number}  ${r.client_name.padEnd(22, " ").slice(0, 22)}  ${formatMoney(r.balance_cents).padStart(12, " ")}  ${
        r.days_overdue > 0 ? `${r.days_overdue}d overdue` : "within terms"
      }`,
  );

  // The table is capped, so it says so, and it says what the cap cost — without
  // this the head's Outstanding figure and the table under it disagree by the
  // money in the rows nobody printed, on the one output a person pastes into an
  // email. Same shape as the footers the WebMCP tools already emit.
  const tail =
    hidden.length > 0
      ? `(showing ${shown.length} of ${outstanding.length}; ${hidden.length} more worth ${formatMoney(
          hidden.reduce((s, r) => s + r.balance_cents, 0),
        )} not listed)`
      : `(showing ${shown.length} of ${outstanding.length})`;

  return [
    ...head,
    "",
    "Still owed",
    "".padEnd(46, "-"),
    ...(rows.length > 0 ? [...rows, tail] : ["Nothing outstanding in this period."]),
    "",
    "Generated by Ledgerbox. Figures come from the books, not an estimate.",
  ].join("\n");
}

/**
 * The same close as Markdown: a heading, the figures as a two-column table, and the capped
 * "Still owed" table under it carrying the same `(showing N of M)` footer the text form does.
 */
export function renderSummaryMarkdown({ summary, outstanding }: SummaryInput): string {
  const shown = outstanding.slice(0, LIMIT);
  const hidden = outstanding.slice(LIMIT);
  const figures: [string, string][] = [
    ["Invoices issued", String(summary.invoice_count)],
    ["Invoiced", formatMoney(summary.invoiced_cents)],
    ["Collected", formatMoney(summary.collected_cents)],
    ["Outstanding", formatMoney(summary.outstanding_cents)],
    ["Overdue", `${formatMoney(summary.overdue_cents)} across ${summary.overdue_count} invoices`],
    ["Disputed", String(summary.disputed_count)],
    ["Bank lines unapplied", `${summary.unmatched_lines} worth ${formatMoney(summary.unmatched_cents)}`],
  ];

  const rows = shown.map(
    (r) =>
      `| ${r.number} | ${r.client_name} | ${formatMoney(r.balance_cents)} | ${
        r.days_overdue > 0 ? `${r.days_overdue}d overdue` : "within terms"
      } |`,
  );

  const tail =
    hidden.length > 0
      ? `_(showing ${shown.length} of ${outstanding.length}; ${hidden.length} more worth ${formatMoney(
          hidden.reduce((sum, r) => sum + r.balance_cents, 0),
        )} not listed)_`
      : `_(showing ${shown.length} of ${outstanding.length})_`;

  return [
    `# ${summaryTitle(summary.period)}`,
    "",
    `Ledgerbox, ${PERIOD_LABEL[summary.period]}. Figures come from the books, not an estimate.`,
    "",
    "| Figure | Value |",
    "| --- | --- |",
    ...figures.map(([label, value]) => `| ${label} | ${value} |`),
    "",
    "## Still owed",
    "",
    ...(rows.length > 0
      ? ["| Invoice | Client | Balance | Age |", "| --- | --- | --- | --- |", ...rows, "", tail]
      : ["Nothing outstanding in this period."]),
  ].join("\n");
}
